-- ============================================================
--  SATs Practice Arena — database setup
--  Run this ONCE in your Supabase project:
--    supabase.com  ->  your project  ->  SQL Editor  ->  New query
--    paste this whole file  ->  Run
--  Safe to run more than once (everything is "if not exists").
--  It does NOT touch your arcade's existing players / scores tables.
-- ============================================================

-- ---------- 1. Accounts ----------
create table if not exists public.sats_players (
  id          bigint generated by default as identity primary key,
  name        text not null,
  name_key    text not null unique,          -- lowercase name, used for lookup
  avatar      text default '🦊',
  pass_hash   text not null,                 -- SHA-256 of (name_key + ':' + password)
  year_group  text default 'Year 6',
  created_at  timestamptz not null default now()
);

-- ---------- 2. Every completed test ----------
create table if not exists public.sats_sessions (
  id            bigint generated by default as identity primary key,
  player_key    text not null,               -- lowercase name of the child
  player        text not null,               -- display name as typed
  subject       text not null,               -- arithmetic | reasoning | gps | reading
  mode          text not null,               -- practice | past | mock
  year          text,                        -- past paper year
  paper         text,                        -- paper name / mock paper
  topic_filter  text,                        -- topic chosen in practice mode
  passage_title text,                        -- reading text title
  questions     integer not null default 0,
  got           integer not null default 0,  -- marks scored
  max           integer not null default 0,  -- marks available
  secs          integer not null default 0,  -- seconds taken
  topics        jsonb   not null default '{}'::jsonb,  -- {"Fractions":{"got":6,"max":8}, ...}
  client_id     text unique,                 -- stops the same test uploading twice
  played_at     timestamptz not null default now()
);

create index if not exists sats_sessions_player_idx
  on public.sats_sessions (player_key, played_at desc);

-- ---------- 3. Row level security ----------
alter table public.sats_players  enable row level security;
alter table public.sats_sessions enable row level security;

-- Accounts: anyone may create one and look one up (needed to log in from any computer).
drop policy if exists "sats_players read"   on public.sats_players;
drop policy if exists "sats_players insert" on public.sats_players;
drop policy if exists "sats_players update" on public.sats_players;
create policy "sats_players read"   on public.sats_players for select using (true);
create policy "sats_players insert" on public.sats_players for insert with check (true);
create policy "sats_players update" on public.sats_players for update using (true) with check (true);

-- Results: readable (so the dashboard works) and insertable. No deletes from the app.
drop policy if exists "sats_sessions read"   on public.sats_sessions;
drop policy if exists "sats_sessions insert" on public.sats_sessions;
create policy "sats_sessions read"   on public.sats_sessions for select using (true);
create policy "sats_sessions insert" on public.sats_sessions for insert with check (true);

-- ---------- 4. Quick check ----------
-- select count(*) from public.sats_players;
-- select * from public.sats_sessions order by played_at desc limit 20;
